name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev" ]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install semver library
        run: pip install semver
      
      - name: Increment version number
        run: |
          current_version=$(cat version.txt)
          next_version=$(python -c "import semver; print(semver.bump_patch('$current_version'))")
          echo "$next_version" > version.txt

      - name: Build Docker Image
        run: docker build . --tag audioe/x265transcoder:dev

      - name: Log in to Docker Hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push Docker Image
        run: docker push audioe/x265transcoder:dev
