name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build . --tag audioe/x265transcoder:latest

      - name: Log in to Docker Hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push Docker Image
        run: docker push audioe/x265transcoder:latest
